version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - crossws
  - defu
  - Elysia
  - elysiajs
  - formkit
  - gramsearch
  - guiiai
  - hahaqwq
  - iconify
  - jieba
  - listhen
  - Logg
  - lucide
  - luoling
  - ofetch
  - ollama
  - onnotice
  - pathe
  - pglite
  - pgvector
  - pinia
  - reka
  - Retriable
  - sonner
  - taze
  - tiktoken
  - trpc
  - tsquery
  - tsvector
  - unocss
  - unplugin
  - uuidv4
  - valibot
  - vitest
  - vueuse
  - xsai
ignoreWords: []
import: []
